### PR TITLE
Use mkdir to make sure only one display is used at a time

### PR DESCRIPTION
**Pull request by pawamoy**
Variant of #101.

Reference: https://github.com/qtile/qtile/issues/1634

### CODE REVIEW

**Comment by tych0** [comment]
I don't see how mkdir is any less racy than open(O_CREAT), I'll just close this in favor of #101

**Comment by pawamoy** [comment]
Because `open(file "w")` doesn't fail if the file already exists, while `os.mkdir(path)` does!

**Comment by tych0** [comment]
Yeah, I'm suggesting that we switch to open(O_CREAT) which would be equivalent. But I like the flock better.

**Comment by pawamoy** [comment]
Sure, no problem :slightly_smiling_face: 

However I tried `os.open(file, os.O_CREAT)` (not sure if this is actually what you mean) and it still doesn't fail if the file already exists.

**Comment by tych0** [comment]
On Sun, Apr 19, 2020 at 09:22:22AM -0700, Timothée Mazzucotelli wrote:
> Sure, no problem :slightly_smiling_face: 
> 
> However I tried `os.open(file, os.O_CREAT)` (not sure if this is actually what you mean) and it still doesn't fail if the file already exists.

Yeah, I think you really need open(O_CREAT|O_EXCL), sorry.

**Pull request closed without merging**
