### PR TITLE
Replace nose by pytest

### PR DESCRIPTION
**Pull request by mcepl**
Helping #116

### CODE REVIEW

**Review by flacjacket — APPROVED** [review]
If everything passes, this looks good to me. I'm not too familiar with nose2 or how it stacks up against pytest to say if this is a better direction.

**Comment by tych0** [comment]
I think nose2 is basically unmaintained at this point, and CI passed, so I'm +1. Thanks for this!

**Comment by tych0** [comment]
Just a heads up, I'm reverting this in an upcoming patch series. Turns out it didn't really run any of the tests, and when I fixed that bit there were a host of problems.

**Comment by mcepl** [comment]
> Just a heads up, I'm reverting this in an upcoming patch series. Turns out it didn't really run any of the tests, and when I fixed that bit there were a host of problems.

Sorry, `pytest` didn't run the tests while `nosetests` did?

Also, I was mistaken, [nose2](https://github.com/nose-devs/nose2) seems quite alive, the problem is the original [nose](https://github.com/nose-devs/nose) seems completely pinning for the fjords.

**Comment by flacjacket** [comment]
Yikes! Good catch @tych0. If pytest is desired, then it might make sense to wrap the `XcffibTest` functionality in a pytest fixture.

**Comment by flacjacket** [comment]
I just put up an alternative fix here that continues to use pytest: #119

**Comment by tych0** [comment]
Great, thanks!

**Pull request merged**
